version: '3.7'
services:
  monorepo:
    image: cenk1cenk2/lerna-dev:16
    environment:
      PACKAGE_START_COMMAND: start
      SERVICES: .
      PREFIX_LABEL: "false"
    ports:
      - 4200:4200
      - 9229:9229
    volumes:
      - .:/data/app
